{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gupshup-matrix.serviceAccountName" . }}
  labels:
{{ include "gupshup-matrix.labels" . | indent 4 }}
{{- end -}}
